language: java

sudo: false

jdk:
  - oraclejdk8

os:
  - linux

script:
  - cd Plugin && mvn test

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false

addons:
    code_climate:
        repo_token: 18c0befcb2a310010eebc4d6c489325f83dfdc62e7b924f3815f120a7f4b39fb
